version: "3.9"

services:
  nicegui:
    build: .
      # image: zauberzeug/nicegui:latest + PIL
    ports:
      - 8080:8080
    volumes:
      - ./app:/app # mounting local app directory
    environment:
      - PUID=1000 # change this to your user id
      - PGID=1000 # change this to your group id
      - STORAGE_SECRET=change-this-to-yor-own-private-secret
      - WEBSITE=http://localhost:8080
      - FOTD_FORMAT=fotd_%d-%m-%Y(%w|%j)
